CREATE TABLE USUARIO(
    ID_USUARIO NUMBER(10)GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE VARCHAR2(30) NOT NULL,
    CORREO VARCHAR2(50) UNIQUE,
    CONTRASEÑA VARCHAR2(30) NOT NULL
);

CREATE TABLE EVENTO(
    ID_EVENTO NUMBER(10) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE VARCHAR2(30) NOT NULL,
    AFORO NUMBER(5) NOT NULL,
    DURACION NUMBER(5,2) NOT NULL,
    UBICACION NUMBER(38) NOT NULL,
    FECHA DATE NOT NULL
);

CREATE TABLE ORGANIZADOR(
    ID_ORGANIZADOR NUMBER(10) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE VARCHAR2(30) NOT NULL,
    CORREO VARCHAR2(50) UNIQUE,
    TELEFONO NUMBER(13) NOT NULL
);

CREATE TABLE CATEGORIA(
    NOMBRE VARCHAR2(30) NOT NULL,
    PRIMARY KEY (NOMBRE)
);

CREATE TABLE INSCRIPCION(
    ID_USUARIO NUMBER(10),
    ID_EVENTO NUMBER(10),
    PRIMARY KEY(ID_USUARIO,ID_EVENTO),
    CONSTRAINT FK_ID_USUARIO FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),
    CONSTRAINT FK_ID_EVENTO FOREIGN KEY(ID_EVENTO) REFERENCES EVENTO(ID_EVENTO)
);

CREATE TABLE ASISTENCIA(
    ID_USUARIO NUMBER(10),
    ID_EVENTO NUMBER(10),
    PRIMARY KEY(ID_USUARIO,ID_EVENTO),
    ASISTE VARCHAR(2) CHECK (ASISTE IN('SI','NO')) NOT NULL,
    CONSTRAINT FK_INSCRIPCION_USUARIO FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),
    CONSTRAINT FK_INSCRIPCION_EVENTO FOREIGN KEY(ID_EVENTO) REFERENCES EVENTO(ID_EVENTO)
);

CREATE TABLE ORGANIZACION(
    ID_EVENTO NUMBER(10),
    ID_ORGANIZADOR NUMBER(10),
    PRIMARY KEY(ID_EVENTO,ID_ORGANIZADOR),
    CONSTRAINT FK_ORGANIZADOR FOREIGN KEY (ID_ORGANIZADOR) REFERENCES ORGANIZADOR(ID_ORGANIZADOR),
    CONSTRAINT FK_ORGANIZADOR_EVENTO FOREIGN KEY (ID_EVENTO) REFERENCES EVENTO(ID_EVENTO)
);

CREATE TABLE CATEGORIA_EVENTO(
    ID_EVENTO NUMBER(10),
    NOMBRE VARCHAR2(30),
    PRIMARY KEY(ID_EVENTO, NOMBRE),
    CONSTRAINT FK_NOMBRE FOREIGN KEY (NOMBRE) REFERENCES CATEGORIA(NOMBRE),
    CONSTRAINT FK_CATEGORIA_EVENTO FOREIGN KEY (ID_EVENTO) REFERENCES EVENTO(ID_EVENTO)
);
